#!/bin/sh
set -x
orig=$1
mkdir -p res/drawable-mdpi
mkdir -p res/drawable-hdpi
mkdir -p res/drawable-xhdpi
mkdir -p res/drawable-xxhdpi
mkdir -p res/drawable-xxxhdpi
sips -z 48 48     $orig --out res/drawable-mdpi/icon.png
sips -z 72 72     $orig --out res/drawable-hdpi/icon.png
sips -z 96 96     $orig --out res/drawable-xhdpi/icon.png
sips -z 144 144   $orig --out res/drawable-xxhdpi/icon.png
sips -z 192 192   $orig --out res/drawable-xxxhdpi/icon.png
