/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muandheyo_lotech_Client */

#ifndef _Included_com_muandheyo_lotech_Client
#define _Included_com_muandheyo_lotech_Client
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
