/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muandheyo_lotech_LotechRenderer */

#ifndef _Included_com_muandheyo_lotech_LotechRenderer
#define _Included_com_muandheyo_lotech_LotechRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muandheyo_lotech_LotechRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muandheyo_lotech_LotechRenderer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_muandheyo_lotech_LotechRenderer
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_muandheyo_lotech_LotechRenderer_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_muandheyo_lotech_LotechRenderer
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muandheyo_lotech_LotechRenderer_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_muandheyo_lotech_LotechRenderer
 * Method:    nativeTeardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_muandheyo_lotech_LotechRenderer_nativeTeardown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
