#!/bin/sh

h=lua_scripts.h
echo "/* THIS FILE IS GENERATED BY $0 */" > $h

for f in `ls lua/*.lua`; do
    name=`basename $f .lua`
    echo "static const char *lt_script_$name = " >> $h
    echo "\"-- $name.lua\\\n\"" >> $h
    cat $f | grep -v "Copyright .* Ian MacLarty" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed 's/^/"/' | sed 's/$/\\n"/' >> $h
    echo ";" >> $h
    echo >> $h
done
